version: "3.7"
services:
  db:
    image: mysql:8.0.23
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - application
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
      - 3000:3000
    depends_on:
      - db
    networks:
      - application
    environment:
      profile: prod
      db_pass: pass
    volumes:
      - ./server/migrations:/migrations
    command: >
      sh -c "sleep 30 && ./server"
  
  webserver:
    tty: true
    restart: always
    container_name: webserver
    image: nginx:1.17.2
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/cert
      - ./webapp/build:/var/www/html
    networks: 
      - application
    depends_on:
      - app
      - db

networks:
  application:
    driver: bridge
